config/routes.rb
Rails.application.routes.draw do
  get 'options/index'

  root 'home#index'

  get '/options', to: 'options#index'

  get '/dashboard', to: 'dashboard#index'
  get '/live/token', to: 'dashboard#live_token'

  get '/login', to: 'login#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/auth_token.rb
class AuthToken < ActiveRecord::Base
  has_one :service_user
end

app/models/live_token.rb
class LiveToken < ActiveRecord::Base
  belongs_to :user
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :service_users
  has_many :users, through: :service_users
end

app/models/service_user.rb
class ServiceUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  belongs_to :auth_token
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :live_tokens
  has_many :service_users
  has_many :services, through: :service_users
  has_many :auth_tokens, through: :service_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  # @return [User]
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  helper_method :current_user, :logged_in?

  # @return [String]
  def destination
    @destination ||= session[:destination]
  end

  # @param [String] destination
  def destination=(destination)
    @destination = destination

    if destination.nil?
      session.delete(:destination)
    else
      session[:destination] = destination
    end
  end

  # @return [Redirecting]
  def redirect_to_destination
    if destination
      tmp_destination = destination
      self.destination = nil

      return redirect_to tmp_destination
    end

    redirect_to root_path
  end

  # @param [User] user
  def current_user=(user)
    @current_user = user

    if user.nil?
      session.delete(:user_id)
    else
      session[:user_id] = user.id
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  MAX_CONNS_PER_USER = 3
  LIVE_TOKEN_LENGTH = 64

  def index
    unless logged_in?
      self.destination = dashboard_path

      redirect_to login_path
    end
  end

  # noinspection RailsChecklist01
  def live_token
    # if unauthenticated...
    unless logged_in?
      # delete the token
      cookies.delete :live_token

      # return 403
      return head :forbidden
    end

    $redis.select($redis_databases[:concurrent_connections])

    # if there's too many concurrent connections for the user
    if $redis.get(current_user.id).to_i >= MAX_CONNS_PER_USER
      # return 429
      return head :too_many_requests
    end

    # get current live_token cookie
    live_token_cookie = cookies[:live_token]

    # if there is a live_token cookie...
    if live_token_cookie
      # find the token in the DB
      # @type [LiveToken]
      live_token = LiveToken
                       .select(:id, :expires_at)
                       .find_by(token: live_token_cookie)

      # if the token was found and it's not expired, return 200
      if live_token && Time.now < live_token.expires_at
        return head :ok
      end
    end

    # if the current live_token cookie does not exist OR it's expired...
    # generate a new live_token cookie and persist it

    token = SecureRandom.base64(LIVE_TOKEN_LENGTH)[0..LIVE_TOKEN_LENGTH - 1]
    expires_at = 2.hour.from_now

    LiveToken.create!(user: current_user,
                      token: token,
                      ip: request.remote_ip,
                      expires_at: expires_at)

    cookies[:live_token] = { value: token,
                             expires: expires_at,
                             domain: 'saso.dev',
                             httponly: true }

    head :created
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    redirect_to root_path if logged_in?
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    self.current_user = find_or_create_user!

    redirect_to_destination
  end

  def destroy
    self.current_user = nil

    redirect_to root_path
  end

  private

  def find_or_create_user!
    auth = request.env['omniauth.auth']

    proper_name, logo_file = get_provider_info auth[:provider].to_s

    # @type [Service]
    service = Service.select(:id).find_or_create_by!(name: auth[:provider],
                                                     proper_name: proper_name,
                                                     logo_file: logo_file)

    # @type [ServiceUser]
    service_user = ServiceUser
                        .select(:id, :user_id, :auth_token_id)
                        .find_or_initialize_by(service: service,
                                               service_unique_id: auth[:uid])

    # @type [AuthToken]
    new_auth_token = AuthToken.new(access: auth[:credentials][:token],
                                   refresh: auth[:credentials][:refresh_token])

    if auth[:credentials][:expires]
      new_auth_token.expires_at = Time.at(auth[:credentials][:expires_at])
    end

    if service_user.new_record?
      # use currently logged in user or create new one
      # @type [User]
      user = current_user || User.create!(name: auth[:info][:name],
                                          email: auth[:info][:email])

      new_auth_token.save!
      service_user.update!(user: user, auth_token: new_auth_token)
    else
      service_user.auth_token.update!(
          new_auth_token.attributes.delete_if { |k, v| v.nil? } )
    end

    puts service_user
    puts service_user.user

    service_user.user
  end

  def get_provider_info(provider)
    case provider
      when 'github'
        return 'GitHub', 'github.svg'
      when 'twitter'
        return 'Twitter', 'twitter.png'
      when 'google'
        return 'Google', 'google.png'
      when 'digitalocean'
        return 'DigitalOcean', 'digitalocean.png'
      when 'facebook'
        return 'Facebook', 'facebook.svg'
      else
        raise "Unknown provider '#{provider}'"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboard/index.html.erb
<% content_for :title do 'Dashboard' end %>

<div class="flex">
  <div id="dashboard"></div>

  <div class="panel-area">
    <a href="<%= options_path %>" class="panel-link">
      <i class="fa fa-cog"></i>
    </a>
  </div>
</div>

<% content_for :javascripts do %>
    <%= javascript_include_tag 'dashboard/dashboard' %>
<% end %>

app/views/home/index.html.erb
<% content_for :title do 'Home' end %>

<main class="content-container">
  <h1>Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>

    <title><%= yield :title %> | Saso</title>
  </head>

  <body>
    <%= render 'partials/header' %>

    <%= yield %>

    <%= render 'partials/footer' %>

    <%= javascript_include_tag 'application' %>

    <%= yield :javascripts %>
  </body>
</html>

app/views/login/index.html.erb
<% content_for :title do 'Login' end %>

<main class="content-container">
  <div class="login-box">
    <h1 class="login-title">Log in with</h1>

    <div class="login-button-row">
      <a class="login-button-link" href="/auth/google">
        <button class="login-button">Google</button>
      </a>

      <a class="login-button-link" href="/auth/github">
        <button class="login-button">GitHub</button>
      </a>

      <a class="login-button-link" href="/auth/facebook">
        <button class="login-button">Facebook</button>
      </a>

      <a class="login-button-link" href="/auth/digitalocean">
        <button class="login-button">DigitalOcean</button>
      </a>

      <a class="login-button-link" href="/auth/twitter">
        <button class="login-button">Twitter</button>
      </a>
    </div>

  </div>
</main>

app/views/options/index.html.erb
<% content_for :title do 'Options' end %>

<main class="content-container options-container">
  <aside class="services-menu">
    <ul class="services-menu-list">
      <% Service.all.each do |s| %>
        <li class="services-menu-item">
          <%= image_tag s.logo_file, class: 'services-menu-item-logo' %>
          <span class="services-menu-item-name">
            <%= s.proper_name %>
          </span>
        </li>
      <% end %>
    </ul>
  </aside>

  <div class="options">
    <% Service.all.each do |s| %>
        <%= render "options/partials/services/#{s.name}.html.erb" %>
    <% end %>
  </div>
</main>

<%# content_for :javascripts do %>
    <%# javascript_include_tag 'options' %>
<%# end %>

app/views/options/partials/services/_digitalocean.html.erb
<form action="/options/github">
  <h1>
    Hasdf
  </h1>
</form>

app/views/options/partials/services/_facebook.html.erb
<form action="/options/github">
  <h1>
    Hasdf
  </h1>
</form>

app/views/options/partials/services/_github.html.erb
<h1>
  GitHub
</h1>

<form action="/options/github">

</form>

app/views/options/partials/services/_google.html.erb
<form action="/options/github">
  <h1>
    Hasdf
  </h1>
</form>

app/views/options/partials/services/_twitter.html.erb
<form action="/options/github">
  <h1>
    Hasdf
  </h1>
</form>

app/views/partials/_header.html.erb
<header class="header">
  <div class="header-content">
    <a class="header-flex" href="<%= root_path %>">
      <%= image_tag 'saso.svg', class: 'header-logo', alt: 'Saso' %>

      <h1 class="header-title">Saso</h1>
    </a>

    <div class="header-spacer"></div>

    <% if logged_in? %>
        <a class="header-button-link" href="<%= dashboard_path %>">
          <button class="header-button">Dashboard</button>
        </a>

        <a class="header-button-link" href="<%= logout_path %>">
          <button class="header-button">Logout</button>
        </a>
    <% else %>
        <a class="header-button-link" href="<%= login_path %>">
          <button class="header-button">Login</button>
        </a>
    <% end %>
  </div>
</header>